const ActionTypes = {
    CLIENT_GET_TORRENTS: 'CLIENT_GET_TORRENTS',
    CLIENT_GET_TORRENTS_SUCCESS: 'CLIENT_GET_TORRENTS_SUCCESS',
    CLIENT_PAUSE_TORRENT: 'CLIENT_PAUSE_TORRENT',
    CLIENT_PAUSE_TORRENT_SUCCESS: 'CLIENT_PAUSE_TORRENT_SUCCESS',
    CLIENT_RESUME_TORRENT: 'CLIENT_RESUME_TORRENT',
    CLIENT_RESUME_TORRENT_SUCCESS: 'CLIENT_RESUME_TORRENT_SUCCESS',
    CLIENT_SELECT_TORRENT: 'CLIENT_SELECT_TORRENT',
};

export default ActionTypes;